name: Daily University Notice Alarm # 워크플로우 이름

on:
  schedule:
    # 매일 한국 시간 오전 11시에 실행 (UTC 기준 2시)
    # Cron 표현식: 분 시 일 월 요일
    - cron: '0 2 * * *' # UTC 2시 = KST 11시
  workflow_dispatch: # 수동 실행을 위한 트리거 추가

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 (최신 Ubuntu 리눅스)

    steps:
    - name: Checkout repository # 저장소 코드 가져오기
      uses: actions/checkout@v4

    - name: Set up Python # 파이썬 환경 설정
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 사용할 파이썬 버전

    - name: Install dependencies # requirements.txt를 사용하여 라이브러리 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run notice script # 파이썬 스크립트 실행
      env:
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KAKAO_ACCESS_TOKEN: ${{ secrets.KAKAO_ACCESS_TOKEN }}
        KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }} # Refresh Token을 전달하도록 수정
      run: python main.py